/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAuthRouteRouteImport } from './routes/_app/_auth/route'
import { Route as AppCoilsRouteImport } from './routes/_app/coils'
import { Route as AppAuthAccessoriesRouteImport } from './routes/_app/_auth/accessories'
import { Route as AppAuthDriverRouteImport } from './routes/_app/_auth/driver'
import { Route as AppAuthLoadingRouteImport } from './routes/_app/_auth/loading'
import { Route as AppAuthProfileRouteImport } from './routes/_app/_auth/profile'
import { Route as AppAuthRollformingRouteImport } from './routes/_app/_auth/rollforming'
import { Route as AppAuthSettingsRouteRouteImport } from './routes/_app/_auth/settings/route'
import { Route as AppAuthShippingRouteImport } from './routes/_app/_auth/shipping'
import { Route as AppAuthStockCardsRouteImport } from './routes/_app/_auth/stock-cards'
import { Route as AppAuthTrimRouteImport } from './routes/_app/_auth/trim'
import { Route as PasswordResetUid64TokenRouteImport } from './routes/password-reset.$uid64.$token'
import { Route as AppAuthSettingsIndexRouteImport } from './routes/_app/_auth/settings/index'
import { Route as AppAuthSettingsColorsRouteImport } from './routes/_app/_auth/settings/colors'
import { Route as AppAuthSettingsLocationTypesRouteImport } from './routes/_app/_auth/settings/location-types'
import { Route as AppAuthSettingsLocationsRouteImport } from './routes/_app/_auth/settings/locations'
import { Route as AppAuthSettingsMachinesRouteImport } from './routes/_app/_auth/settings/machines'
import { Route as AppAuthSettingsPrioritiesRouteImport } from './routes/_app/_auth/settings/priorities'
import { Route as AppAuthSettingsTrucksRouteImport } from './routes/_app/_auth/settings/trucks'
import { Route as AppAuthSettingsUsersRouteImport } from './routes/_app/_auth/settings/users'
import { Route as AppAuthSettingsWarehousesRouteImport } from './routes/_app/_auth/settings/warehouses'
import { Route as AppAuthSettingsWorkDaysRouteImport } from './routes/_app/_auth/settings/work-days'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAuthRouteRoute = AppAuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCoilsRoute = AppCoilsRouteImport.update({
  id: '/coils',
  path: '/coils',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAuthAccessoriesRoute = AppAuthAccessoriesRouteImport.update({
  id: '/accessories',
  path: '/accessories',
  getParentRoute: () => AppAuthRouteRoute,
} as any)
const AppAuthDriverRoute = AppAuthDriverRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => AppAuthRouteRoute,
} as any)
const AppAuthLoadingRoute = AppAuthLoadingRouteImport.update({
  id: '/loading',
  path: '/loading',
  getParentRoute: () => AppAuthRouteRoute,
} as any)
const AppAuthProfileRoute = AppAuthProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppAuthRouteRoute,
} as any)
const AppAuthRollformingRoute = AppAuthRollformingRouteImport.update({
  id: '/rollforming',
  path: '/rollforming',
  getParentRoute: () => AppAuthRouteRoute,
} as any)
const AppAuthSettingsRouteRoute = AppAuthSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppAuthRouteRoute,
} as any)
const AppAuthShippingRoute = AppAuthShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => AppAuthRouteRoute,
} as any)
const AppAuthStockCardsRoute = AppAuthStockCardsRouteImport.update({
  id: '/stock-cards',
  path: '/stock-cards',
  getParentRoute: () => AppAuthRouteRoute,
} as any)
const AppAuthTrimRoute = AppAuthTrimRouteImport.update({
  id: '/trim',
  path: '/trim',
  getParentRoute: () => AppAuthRouteRoute,
} as any)
const PasswordResetUid64TokenRoute = PasswordResetUid64TokenRouteImport.update({
  id: '/password-reset/$uid64/$token',
  path: '/password-reset/$uid64/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAuthSettingsIndexRoute = AppAuthSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAuthSettingsRouteRoute,
} as any)
const AppAuthSettingsColorsRoute = AppAuthSettingsColorsRouteImport.update({
  id: '/colors',
  path: '/colors',
  getParentRoute: () => AppAuthSettingsRouteRoute,
} as any)
const AppAuthSettingsLocationTypesRoute =
  AppAuthSettingsLocationTypesRouteImport.update({
    id: '/location-types',
    path: '/location-types',
    getParentRoute: () => AppAuthSettingsRouteRoute,
  } as any)
const AppAuthSettingsLocationsRoute =
  AppAuthSettingsLocationsRouteImport.update({
    id: '/locations',
    path: '/locations',
    getParentRoute: () => AppAuthSettingsRouteRoute,
  } as any)
const AppAuthSettingsMachinesRoute = AppAuthSettingsMachinesRouteImport.update({
  id: '/machines',
  path: '/machines',
  getParentRoute: () => AppAuthSettingsRouteRoute,
} as any)
const AppAuthSettingsPrioritiesRoute =
  AppAuthSettingsPrioritiesRouteImport.update({
    id: '/priorities',
    path: '/priorities',
    getParentRoute: () => AppAuthSettingsRouteRoute,
  } as any)
const AppAuthSettingsTrucksRoute = AppAuthSettingsTrucksRouteImport.update({
  id: '/trucks',
  path: '/trucks',
  getParentRoute: () => AppAuthSettingsRouteRoute,
} as any)
const AppAuthSettingsUsersRoute = AppAuthSettingsUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppAuthSettingsRouteRoute,
} as any)
const AppAuthSettingsWarehousesRoute =
  AppAuthSettingsWarehousesRouteImport.update({
    id: '/warehouses',
    path: '/warehouses',
    getParentRoute: () => AppAuthSettingsRouteRoute,
  } as any)
const AppAuthSettingsWorkDaysRoute = AppAuthSettingsWorkDaysRouteImport.update({
  id: '/work-days',
  path: '/work-days',
  getParentRoute: () => AppAuthSettingsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/coils': typeof AppCoilsRoute
  '/settings': typeof AppAuthSettingsRouteRouteWithChildren
  '/accessories': typeof AppAuthAccessoriesRoute
  '/driver': typeof AppAuthDriverRoute
  '/loading': typeof AppAuthLoadingRoute
  '/profile': typeof AppAuthProfileRoute
  '/rollforming': typeof AppAuthRollformingRoute
  '/shipping': typeof AppAuthShippingRoute
  '/stock-cards': typeof AppAuthStockCardsRoute
  '/trim': typeof AppAuthTrimRoute
  '/password-reset/$uid64/$token': typeof PasswordResetUid64TokenRoute
  '/settings/colors': typeof AppAuthSettingsColorsRoute
  '/settings/location-types': typeof AppAuthSettingsLocationTypesRoute
  '/settings/locations': typeof AppAuthSettingsLocationsRoute
  '/settings/machines': typeof AppAuthSettingsMachinesRoute
  '/settings/priorities': typeof AppAuthSettingsPrioritiesRoute
  '/settings/trucks': typeof AppAuthSettingsTrucksRoute
  '/settings/users': typeof AppAuthSettingsUsersRoute
  '/settings/warehouses': typeof AppAuthSettingsWarehousesRoute
  '/settings/work-days': typeof AppAuthSettingsWorkDaysRoute
  '/settings/': typeof AppAuthSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/': typeof AppIndexRoute
  '/coils': typeof AppCoilsRoute
  '/accessories': typeof AppAuthAccessoriesRoute
  '/driver': typeof AppAuthDriverRoute
  '/loading': typeof AppAuthLoadingRoute
  '/profile': typeof AppAuthProfileRoute
  '/rollforming': typeof AppAuthRollformingRoute
  '/shipping': typeof AppAuthShippingRoute
  '/stock-cards': typeof AppAuthStockCardsRoute
  '/trim': typeof AppAuthTrimRoute
  '/password-reset/$uid64/$token': typeof PasswordResetUid64TokenRoute
  '/settings/colors': typeof AppAuthSettingsColorsRoute
  '/settings/location-types': typeof AppAuthSettingsLocationTypesRoute
  '/settings/locations': typeof AppAuthSettingsLocationsRoute
  '/settings/machines': typeof AppAuthSettingsMachinesRoute
  '/settings/priorities': typeof AppAuthSettingsPrioritiesRoute
  '/settings/trucks': typeof AppAuthSettingsTrucksRoute
  '/settings/users': typeof AppAuthSettingsUsersRoute
  '/settings/warehouses': typeof AppAuthSettingsWarehousesRoute
  '/settings/work-days': typeof AppAuthSettingsWorkDaysRoute
  '/settings': typeof AppAuthSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/_app/_auth': typeof AppAuthRouteRouteWithChildren
  '/_app/coils': typeof AppCoilsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/_auth/settings': typeof AppAuthSettingsRouteRouteWithChildren
  '/_app/_auth/accessories': typeof AppAuthAccessoriesRoute
  '/_app/_auth/driver': typeof AppAuthDriverRoute
  '/_app/_auth/loading': typeof AppAuthLoadingRoute
  '/_app/_auth/profile': typeof AppAuthProfileRoute
  '/_app/_auth/rollforming': typeof AppAuthRollformingRoute
  '/_app/_auth/shipping': typeof AppAuthShippingRoute
  '/_app/_auth/stock-cards': typeof AppAuthStockCardsRoute
  '/_app/_auth/trim': typeof AppAuthTrimRoute
  '/password-reset/$uid64/$token': typeof PasswordResetUid64TokenRoute
  '/_app/_auth/settings/colors': typeof AppAuthSettingsColorsRoute
  '/_app/_auth/settings/location-types': typeof AppAuthSettingsLocationTypesRoute
  '/_app/_auth/settings/locations': typeof AppAuthSettingsLocationsRoute
  '/_app/_auth/settings/machines': typeof AppAuthSettingsMachinesRoute
  '/_app/_auth/settings/priorities': typeof AppAuthSettingsPrioritiesRoute
  '/_app/_auth/settings/trucks': typeof AppAuthSettingsTrucksRoute
  '/_app/_auth/settings/users': typeof AppAuthSettingsUsersRoute
  '/_app/_auth/settings/warehouses': typeof AppAuthSettingsWarehousesRoute
  '/_app/_auth/settings/work-days': typeof AppAuthSettingsWorkDaysRoute
  '/_app/_auth/settings/': typeof AppAuthSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/coils'
    | '/settings'
    | '/accessories'
    | '/driver'
    | '/loading'
    | '/profile'
    | '/rollforming'
    | '/shipping'
    | '/stock-cards'
    | '/trim'
    | '/password-reset/$uid64/$token'
    | '/settings/colors'
    | '/settings/location-types'
    | '/settings/locations'
    | '/settings/machines'
    | '/settings/priorities'
    | '/settings/trucks'
    | '/settings/users'
    | '/settings/warehouses'
    | '/settings/work-days'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/login'
    | '/'
    | '/coils'
    | '/accessories'
    | '/driver'
    | '/loading'
    | '/profile'
    | '/rollforming'
    | '/shipping'
    | '/stock-cards'
    | '/trim'
    | '/password-reset/$uid64/$token'
    | '/settings/colors'
    | '/settings/location-types'
    | '/settings/locations'
    | '/settings/machines'
    | '/settings/priorities'
    | '/settings/trucks'
    | '/settings/users'
    | '/settings/warehouses'
    | '/settings/work-days'
    | '/settings'
  id:
    | '__root__'
    | '/_app'
    | '/forgot-password'
    | '/login'
    | '/_app/_auth'
    | '/_app/coils'
    | '/_app/'
    | '/_app/_auth/settings'
    | '/_app/_auth/accessories'
    | '/_app/_auth/driver'
    | '/_app/_auth/loading'
    | '/_app/_auth/profile'
    | '/_app/_auth/rollforming'
    | '/_app/_auth/shipping'
    | '/_app/_auth/stock-cards'
    | '/_app/_auth/trim'
    | '/password-reset/$uid64/$token'
    | '/_app/_auth/settings/colors'
    | '/_app/_auth/settings/location-types'
    | '/_app/_auth/settings/locations'
    | '/_app/_auth/settings/machines'
    | '/_app/_auth/settings/priorities'
    | '/_app/_auth/settings/trucks'
    | '/_app/_auth/settings/users'
    | '/_app/_auth/settings/warehouses'
    | '/_app/_auth/settings/work-days'
    | '/_app/_auth/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PasswordResetUid64TokenRoute: typeof PasswordResetUid64TokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/_auth': {
      id: '/_app/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppAuthRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/coils': {
      id: '/_app/coils'
      path: '/coils'
      fullPath: '/coils'
      preLoaderRoute: typeof AppCoilsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/_auth/accessories': {
      id: '/_app/_auth/accessories'
      path: '/accessories'
      fullPath: '/accessories'
      preLoaderRoute: typeof AppAuthAccessoriesRouteImport
      parentRoute: typeof AppAuthRouteRoute
    }
    '/_app/_auth/driver': {
      id: '/_app/_auth/driver'
      path: '/driver'
      fullPath: '/driver'
      preLoaderRoute: typeof AppAuthDriverRouteImport
      parentRoute: typeof AppAuthRouteRoute
    }
    '/_app/_auth/loading': {
      id: '/_app/_auth/loading'
      path: '/loading'
      fullPath: '/loading'
      preLoaderRoute: typeof AppAuthLoadingRouteImport
      parentRoute: typeof AppAuthRouteRoute
    }
    '/_app/_auth/profile': {
      id: '/_app/_auth/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppAuthProfileRouteImport
      parentRoute: typeof AppAuthRouteRoute
    }
    '/_app/_auth/rollforming': {
      id: '/_app/_auth/rollforming'
      path: '/rollforming'
      fullPath: '/rollforming'
      preLoaderRoute: typeof AppAuthRollformingRouteImport
      parentRoute: typeof AppAuthRouteRoute
    }
    '/_app/_auth/settings': {
      id: '/_app/_auth/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppAuthSettingsRouteRouteImport
      parentRoute: typeof AppAuthRouteRoute
    }
    '/_app/_auth/shipping': {
      id: '/_app/_auth/shipping'
      path: '/shipping'
      fullPath: '/shipping'
      preLoaderRoute: typeof AppAuthShippingRouteImport
      parentRoute: typeof AppAuthRouteRoute
    }
    '/_app/_auth/stock-cards': {
      id: '/_app/_auth/stock-cards'
      path: '/stock-cards'
      fullPath: '/stock-cards'
      preLoaderRoute: typeof AppAuthStockCardsRouteImport
      parentRoute: typeof AppAuthRouteRoute
    }
    '/_app/_auth/trim': {
      id: '/_app/_auth/trim'
      path: '/trim'
      fullPath: '/trim'
      preLoaderRoute: typeof AppAuthTrimRouteImport
      parentRoute: typeof AppAuthRouteRoute
    }
    '/password-reset/$uid64/$token': {
      id: '/password-reset/$uid64/$token'
      path: '/password-reset/$uid64/$token'
      fullPath: '/password-reset/$uid64/$token'
      preLoaderRoute: typeof PasswordResetUid64TokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/_auth/settings/': {
      id: '/_app/_auth/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppAuthSettingsIndexRouteImport
      parentRoute: typeof AppAuthSettingsRouteRoute
    }
    '/_app/_auth/settings/colors': {
      id: '/_app/_auth/settings/colors'
      path: '/colors'
      fullPath: '/settings/colors'
      preLoaderRoute: typeof AppAuthSettingsColorsRouteImport
      parentRoute: typeof AppAuthSettingsRouteRoute
    }
    '/_app/_auth/settings/location-types': {
      id: '/_app/_auth/settings/location-types'
      path: '/location-types'
      fullPath: '/settings/location-types'
      preLoaderRoute: typeof AppAuthSettingsLocationTypesRouteImport
      parentRoute: typeof AppAuthSettingsRouteRoute
    }
    '/_app/_auth/settings/locations': {
      id: '/_app/_auth/settings/locations'
      path: '/locations'
      fullPath: '/settings/locations'
      preLoaderRoute: typeof AppAuthSettingsLocationsRouteImport
      parentRoute: typeof AppAuthSettingsRouteRoute
    }
    '/_app/_auth/settings/machines': {
      id: '/_app/_auth/settings/machines'
      path: '/machines'
      fullPath: '/settings/machines'
      preLoaderRoute: typeof AppAuthSettingsMachinesRouteImport
      parentRoute: typeof AppAuthSettingsRouteRoute
    }
    '/_app/_auth/settings/priorities': {
      id: '/_app/_auth/settings/priorities'
      path: '/priorities'
      fullPath: '/settings/priorities'
      preLoaderRoute: typeof AppAuthSettingsPrioritiesRouteImport
      parentRoute: typeof AppAuthSettingsRouteRoute
    }
    '/_app/_auth/settings/trucks': {
      id: '/_app/_auth/settings/trucks'
      path: '/trucks'
      fullPath: '/settings/trucks'
      preLoaderRoute: typeof AppAuthSettingsTrucksRouteImport
      parentRoute: typeof AppAuthSettingsRouteRoute
    }
    '/_app/_auth/settings/users': {
      id: '/_app/_auth/settings/users'
      path: '/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof AppAuthSettingsUsersRouteImport
      parentRoute: typeof AppAuthSettingsRouteRoute
    }
    '/_app/_auth/settings/warehouses': {
      id: '/_app/_auth/settings/warehouses'
      path: '/warehouses'
      fullPath: '/settings/warehouses'
      preLoaderRoute: typeof AppAuthSettingsWarehousesRouteImport
      parentRoute: typeof AppAuthSettingsRouteRoute
    }
    '/_app/_auth/settings/work-days': {
      id: '/_app/_auth/settings/work-days'
      path: '/work-days'
      fullPath: '/settings/work-days'
      preLoaderRoute: typeof AppAuthSettingsWorkDaysRouteImport
      parentRoute: typeof AppAuthSettingsRouteRoute
    }
  }
}

interface AppAuthSettingsRouteRouteChildren {
  AppAuthSettingsColorsRoute: typeof AppAuthSettingsColorsRoute
  AppAuthSettingsLocationTypesRoute: typeof AppAuthSettingsLocationTypesRoute
  AppAuthSettingsLocationsRoute: typeof AppAuthSettingsLocationsRoute
  AppAuthSettingsMachinesRoute: typeof AppAuthSettingsMachinesRoute
  AppAuthSettingsPrioritiesRoute: typeof AppAuthSettingsPrioritiesRoute
  AppAuthSettingsTrucksRoute: typeof AppAuthSettingsTrucksRoute
  AppAuthSettingsUsersRoute: typeof AppAuthSettingsUsersRoute
  AppAuthSettingsWarehousesRoute: typeof AppAuthSettingsWarehousesRoute
  AppAuthSettingsWorkDaysRoute: typeof AppAuthSettingsWorkDaysRoute
  AppAuthSettingsIndexRoute: typeof AppAuthSettingsIndexRoute
}

const AppAuthSettingsRouteRouteChildren: AppAuthSettingsRouteRouteChildren = {
  AppAuthSettingsColorsRoute: AppAuthSettingsColorsRoute,
  AppAuthSettingsLocationTypesRoute: AppAuthSettingsLocationTypesRoute,
  AppAuthSettingsLocationsRoute: AppAuthSettingsLocationsRoute,
  AppAuthSettingsMachinesRoute: AppAuthSettingsMachinesRoute,
  AppAuthSettingsPrioritiesRoute: AppAuthSettingsPrioritiesRoute,
  AppAuthSettingsTrucksRoute: AppAuthSettingsTrucksRoute,
  AppAuthSettingsUsersRoute: AppAuthSettingsUsersRoute,
  AppAuthSettingsWarehousesRoute: AppAuthSettingsWarehousesRoute,
  AppAuthSettingsWorkDaysRoute: AppAuthSettingsWorkDaysRoute,
  AppAuthSettingsIndexRoute: AppAuthSettingsIndexRoute,
}

const AppAuthSettingsRouteRouteWithChildren =
  AppAuthSettingsRouteRoute._addFileChildren(AppAuthSettingsRouteRouteChildren)

interface AppAuthRouteRouteChildren {
  AppAuthSettingsRouteRoute: typeof AppAuthSettingsRouteRouteWithChildren
  AppAuthAccessoriesRoute: typeof AppAuthAccessoriesRoute
  AppAuthDriverRoute: typeof AppAuthDriverRoute
  AppAuthLoadingRoute: typeof AppAuthLoadingRoute
  AppAuthProfileRoute: typeof AppAuthProfileRoute
  AppAuthRollformingRoute: typeof AppAuthRollformingRoute
  AppAuthShippingRoute: typeof AppAuthShippingRoute
  AppAuthStockCardsRoute: typeof AppAuthStockCardsRoute
  AppAuthTrimRoute: typeof AppAuthTrimRoute
}

const AppAuthRouteRouteChildren: AppAuthRouteRouteChildren = {
  AppAuthSettingsRouteRoute: AppAuthSettingsRouteRouteWithChildren,
  AppAuthAccessoriesRoute: AppAuthAccessoriesRoute,
  AppAuthDriverRoute: AppAuthDriverRoute,
  AppAuthLoadingRoute: AppAuthLoadingRoute,
  AppAuthProfileRoute: AppAuthProfileRoute,
  AppAuthRollformingRoute: AppAuthRollformingRoute,
  AppAuthShippingRoute: AppAuthShippingRoute,
  AppAuthStockCardsRoute: AppAuthStockCardsRoute,
  AppAuthTrimRoute: AppAuthTrimRoute,
}

const AppAuthRouteRouteWithChildren = AppAuthRouteRoute._addFileChildren(
  AppAuthRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppAuthRouteRoute: typeof AppAuthRouteRouteWithChildren
  AppCoilsRoute: typeof AppCoilsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAuthRouteRoute: AppAuthRouteRouteWithChildren,
  AppCoilsRoute: AppCoilsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PasswordResetUid64TokenRoute: PasswordResetUid64TokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
